name: MacOS

on: [pull_request]

jobs:
  macos-clang:
    runs-on: macos-latest
    env:
      CMAKE_FLAGS: '-DSERDEPP_USE_NLOHMANN_JSON=ON -DSERDEPP_USE_TOML11=ON -DSERDEPP_USE_YAML-CPP=ON -DSERDEPP_BUILD_EXAMPLES=ON'
    strategy:
      matrix:
        build-type: ['Release', 'Debug']
    steps:
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
    - name: Clone Repository
      uses: actions/checkout@master
      with:
        submodules: true
    - name: C++ Setting
      run: |
        brew install llvm cmake
    - name: Compiler Setting
      run: |
        echo "CC=/usr/local/opt/llvm/bin/clang" >> $GITHUB_ENV
        echo "CXX=/usr/local/opt/llvm/bin/clang++" >> $GITHUB_ENV
    - name: CMake build
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.build-type}} ${{env.CMAKE_FLAGS}} .
        cd build
        cmake --build . --config ${{matrix.build-type}}
    - name: Run Test Script
      run: |
        cd build/${{matrix.build-type}}
        ./serde_example
        ./serde_example1
        ./simple_example

